config/routes.rb
Backend::Application.routes.draw do

  resources :samples

  resources :users
  resources :sessions
  resources :bookdetails
  resources :genres
  post '/login' , to: 'sessions#index'
  get '/details', to: 'users#show'

end

app/models/bookdetail.rb
class Bookdetail < ActiveRecord::Base
  attr_accessible :bookname, :author, :price, :description, :genre_id
  belongs_to :genre
  
 end

app/models/discoverbooks.rb
class Discoverbooks < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :genre
  has_many :bookdetails
  has_and_belongs_to_many :users
  scope :with_name, lambda{ |name| where(genre: name) }
end

app/models/user.rb
class User < ActiveRecord::Base
	
  attr_accessible :firstname, :lastname, :email, :password, :genre
  validates :email, uniqueness: {message: 'Email already exists'}
  has_and_belongs_to_many :genres
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/bookdetails_controller.rb
class BookdetailsController < ApplicationController
	def create
		
		book = Bookdetail.new(bookname:params[:bookdetails][:bookname],author:params[:bookdetails][:author],
								price:params[:bookdetails][:price],description:params[:bookdetails][:description])
			book.genre = Genre.find_by_genre(params[:bookdetails][:genre])
		if book.save
			render json: book
		else
			render json: {error: "failed"}
		end
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	def index
	@genres = Genre.all
	render :json => {genres: @genres}
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	 protect_from_forgery with: :null_session
	def show

		render json: User.all

	end
	def index
		
			  current_user = User.find{|x| x.email == params[:email] && x.password == params[:password]}
      if current_user.present?
      
          session[:user_id] = current_user.id
            render json: {sucess: "logged in successfully"}, status: 201
        else
            render json: {error: "Incorrect username or password"}, status: 401
        
        end

	   
	     
	      	

	end
	
	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



def create
		
	@user = User.new(firstname:params[:user][:firstname],lastname:params[:user][:lastname],email:params[:user][:email],password:params[:user][:password])
	#byebug
	params[:user][:selected_genre].split(',').each do |genre|
		@user.genres.push(Genre.find_by_genre(genre))
	end
	if @user.save
		render :json => {user: @user}

		#flash[:notice]  = 'Sign in successful'
	else
		render :json => {error: @user.errors}
	end
end
def show
	
	g = User.find_by_email(params[:email]).genres
	genre_ids = []
	g.each {|genre| genre_ids.push(genre.id)}
	@books = Bookdetail.where("genre_id in (#{genre_ids.join(',')})")
	render :json => {books: @books}
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookdetails_helper.rb
module BookdetailsHelper
end

app/helpers/discoverbook_helper.rb
module DiscoverbookHelper
end

app/helpers/discoverbooks_helper.rb
module DiscoverbooksHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backend</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @samples.each do |sample| %>
  <tr>
    <td><%= link_to 'Show', sample %></td>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
    <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>